#! /bin/bash

CERTFILE=/usr/share/nginx-opi/opi-tmpcert.pem
KEYFILE=/usr/share/nginx-opi/opi-tmpkey.pem

#CERTFILE=testcert.pem
#KEYFILE=testkey.pem

openssl req -nodes  -x509 -newkey rsa:4096 -keyout $KEYFILE -out $CERTFILE -days 3650 2>/dev/null << EOF
SE
.
.
Kinguard Project
.
tempname.kinguardproject.org
.
EOF

# Make sure permissions are sane
chmod 0640 /usr/share/nginx-opi/opi-tmpkey.pem
chown root:ssl-cert /usr/share/nginx-opi/opi-tmpkey.pem
